### PR TITLE
Fix spelling in readme

### PR DESCRIPTION
**Pull request by Emiluren**
I also specified that it is only necessary to run the client in release mode.

### CODE REVIEW

**Comment by TheZoq2** [comment]
Does the server not benefit from running in release mode?

**Comment by Emiluren** [comment]
nyet

**Comment by TheZoq2** [comment]
Ok comrade

**Review by TheZoq2 — APPROVED** [review]

**Review by malcx95 — COMMENTED** [review]
is gud

**Review by malcx95 — APPROVED** [review]

**Pull request merged**
